export type Alert = {
  id: string;
  severity: "info" | "warning" | "danger";
  title: { fr: string; en: string };
  body: { fr: string; en: string };
  tag: { fr: string; en: string };
};

export const ALERTS: Alert[] = [
  {
    id: "a1",
    severity: "danger",
    title: {
      fr: "Faux Amoxicilline en circulation",
      en: "Fake Amoxicillin in circulation",
    },
    body: {
      fr: "Des blisters contrefaits sans hologramme sont signalés à Douala et Bafoussam. Vérifiez le lot et refusez les emballages abîmés.",
      en: "Counterfeit blisters without hologram are reported in Douala and Bafoussam. Check the batch and reject damaged packaging.",
    },
    tag: { fr: "Contrefaçon", en: "Counterfeit" },
  },
  {
    id: "a2",
    severity: "warning",
    title: {
      fr: "Arnaques ordonnances WhatsApp",
      en: "WhatsApp prescription scams",
    },
    body: {
      fr: "Ne payez jamais un « médecin » qui envoie une ordonnance par WhatsApp sans consultation. Faites vérifier par MedLocs.",
      en: "Never pay a 'doctor' who sends a prescription via WhatsApp without a consultation. Have it verified by MedLocs.",
    },
    tag: { fr: "Cybersécurité", en: "Cybersecurity" },
  },
  {
    id: "a3",
    severity: "info",
    title: {
      fr: "IA & santé : restez prudent",
      en: "AI & health: stay cautious",
    },
    body: {
      fr: "Les conseils générés par ChatGPT ou TikTok ne remplacent JAMAIS un médecin. Consultez une officine agréée.",
      en: "Advice generated by ChatGPT or TikTok NEVER replaces a doctor. Consult an approved pharmacy.",
    },
    tag: { fr: "Éducation", en: "Education" },
  },
];

// Conseils officiels du Ministère de la Santé Publique du Cameroun
// Curated tips from the Ministry of Public Health of Cameroon
export type Tip = {
  id: string;
  category: { fr: string; en: string };
  title: { fr: string; en: string };
  body: { fr: string; en: string };
  source: string;
};

export const MINISTRY_TIPS: Tip[] = [
  {
    id: "t1",
    category: { fr: "Anti-automédication", en: "Anti-self-medication" },
    title: {
      fr: "Ne jamais prendre d'antibiotiques sans ordonnance",
      en: "Never take antibiotics without a prescription",
    },
    body: {
      fr: "L'automédication en antibiotiques favorise la résistance bactérienne. Un mauvais dosage rend les infections futures incurables. Consultez toujours un médecin ou un pharmacien agréé.",
      en: "Self-medicating with antibiotics fuels bacterial resistance. Wrong dosing makes future infections untreatable. Always consult a doctor or an approved pharmacist.",
    },
    source: "MINSANTÉ Cameroun",
  },
  {
    id: "t2",
    category: { fr: "Achats sûrs", en: "Safe purchases" },
    title: {
      fr: "N'achetez jamais de médicaments dans la rue",
      en: "Never buy medications on the street",
    },
    body: {
      fr: "Les médicaments vendus au marché ou en bord de route ne respectent pas la chaîne du froid et peuvent contenir de la craie ou du plâtre. Achetez uniquement en pharmacie agréée.",
      en: "Medications sold at markets or on the roadside break the cold chain and may contain chalk or plaster. Buy only from approved pharmacies.",
    },
    source: "MINSANTÉ Cameroun",
  },
  {
    id: "t3",
    category: { fr: "Vérification", en: "Verification" },
    title: {
      fr: "Vérifier l'emballage : 4 signes à contrôler",
      en: "Check the packaging: 4 signs to verify",
    },
    body: {
      fr: "1) Hologramme officiel présent. 2) Numéro de lot et date de péremption lisibles. 3) Notice en français ou anglais correcte. 4) Blister intact et propre. Un doute ? Scanner via MedLocs.",
      en: "1) Official hologram present. 2) Batch number and expiry date legible. 3) Proper leaflet in French or English. 4) Intact and clean blister. In doubt? Scan via MedLocs.",
    },
    source: "OMS / MINSANTÉ",
  },
  {
    id: "t4",
    category: { fr: "Enfants & grossesse", en: "Children & pregnancy" },
    title: {
      fr: "Aspirine interdite avant 16 ans",
      en: "Aspirin banned under age 16",
    },
    body: {
      fr: "L'aspirine peut provoquer le syndrome de Reye chez l'enfant. Pour la fièvre chez les enfants, privilégiez le paracétamol au dosage adapté au poids.",
      en: "Aspirin can trigger Reye syndrome in children. For fever in children, prefer paracetamol dosed by weight.",
    },
    source: "MINSANTÉ Cameroun",
  },
  {
    id: "t5",
    category: { fr: "Paludisme", en: "Malaria" },
    title: {
      fr: "Fièvre + fatigue : test paludisme obligatoire",
      en: "Fever + fatigue: malaria test is mandatory",
    },
    body: {
      fr: "Ne prenez pas d'antipaludéen à l'aveugle. Un TDR (test rapide) coûte moins de 500 FCFA et évite les traitements inutiles qui abîment le foie.",
      en: "Do not take antimalarials blindly. A rapid test costs under 500 FCFA and prevents useless treatments that damage the liver.",
    },
    source: "PNLP Cameroun",
  },
  {
    id: "t6",
    category: { fr: "Conservation", en: "Storage" },
    title: {
      fr: "Ne stockez pas les médicaments dans la salle de bain",
      en: "Do not store medications in the bathroom",
    },
    body: {
      fr: "L'humidité et la chaleur dégradent les principes actifs. Rangez au sec, à moins de 25°C, à l'abri du soleil et hors de portée des enfants.",
      en: "Humidity and heat degrade active ingredients. Store in a dry place under 25°C, away from sunlight and out of reach of children.",
    },
    source: "MINSANTÉ Cameroun",
  },
  {
    id: "t7",
    category: { fr: "Numérique", en: "Digital" },
    title: {
      fr: "Méfiez-vous des « miracles » vus sur TikTok",
      en: "Beware of 'miracles' seen on TikTok",
    },
    body: {
      fr: "Aucune tisane, huile ou complément vu sur les réseaux ne guérit le diabète, le VIH ou le cancer. Signalez ces contenus et alertez vos proches.",
      en: "No herbal tea, oil or supplement seen on social media cures diabetes, HIV or cancer. Report such content and alert your loved ones.",
    },
    source: "MINSANTÉ · ANTIC",
  },
  {
    id: "t8",
    category: { fr: "Vaccination", en: "Vaccination" },
    title: {
      fr: "Suivez le calendrier PEV pour vos enfants",
      en: "Follow the EPI schedule for your children",
    },
    body: {
      fr: "Le Programme Élargi de Vaccination protège gratuitement contre 13 maladies. Renseignez-vous au centre de santé le plus proche.",
      en: "The Expanded Programme on Immunization protects free of charge against 13 diseases. Ask at your nearest health centre.",
    },
    source: "PEV Cameroun",
  },
];
